language: groovy
jobs:
  include:
  - stage: Build plugin
    os: linux
    jdk: oraclejdk9
    script:
      - ./gradlew clean build
  - stage: Deploy
    os: linux
    jdk: oraclejdk9
    script: skip
    deploy:
      provider: script
      script:
        - ./gradlew clean publishPlugins -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET
      on:
        tags: true
  - stage: Deploy
    script: skip
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      on:
        tags: true
  - stage: Build example
    os: linux
    jdk: oraclejdk8
    script:
      - cd examples/go-and-dep
      - ../../gradlew clean build
      - cd ../go-and-disabled-modules
      - ../../gradlew clean build
  - stage: Build example
    os: linux
    jdk: oraclejdk9
    script:
      - cd examples/go-and-dep
      - ../../gradlew clean build
      - cd ../go-and-disabled-modules
      - ../../gradlew clean build
  - stage: Build example
    os: osx
    osx_image: xcode9.3beta
    env:
      - GOPATH=$HOME/go
      - PATH=$PATH:$GOPATH/bin
    script:
      - cd examples/go-and-dep
      - ../../gradlew clean build
      - cd ../go-and-disabled-modules
      - ../../gradlew clean build
    before_install:
      - mkdir -p $HOME/go/bin
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false
